import type { FinalEvaluation } from "../../lib/gradeFinalization";

// Preserve the original scoring while adding detail generated by the server.
export function mergeDetailedEvaluation<T extends FinalEvaluation>(original: T, detailed: FinalEvaluation): T {
  if (detailed.access_tier === "free" || detailed.criteria.length !== original.criteria.length) throw new Error("DETAILED_EVALUATION_INVALID");
  return {
    ...original,
    access_tier: detailed.access_tier,
    top_improvements: detailed.top_improvements,
    criteria: original.criteria.map((criterion, index) => {
      const detail = detailed.criteria[index];
      if (detail.name !== criterion.name || !detail.detailed_breakdown?.trim()) throw new Error("DETAILED_EVALUATION_INVALID");
      return {
        ...criterion, detailed_breakdown: detail.detailed_breakdown, detailed_breakdown_locked: false,
        ...(detail.example_revisions ? { example_revisions: detail.example_revisions } : {}),
      };
    }),
  };
}
